server/registration_form/portal/urls.py
# ----------------------------------------------------------------------- #
# Copyright (C) 2014-2015 Federico "MrModd" Cosentino (http://mrmodd.it/) #
# on behalf of Roma2LUG (http://lug.uniroma2.it/)                         #
# ----------------------------------------------------------------------- #

from django.conf.urls import patterns, url, include

from portal import views

urlpatterns = patterns('',
	
	# Registration form
	url(r'^$', views.index, name='index'),
	url(r'^participants$', views.participant_list, name='participants'),
	url(r'^participants/morning$', views.morning_users, name='morning_users'),
	url(r'^participants/afternoon$', views.afternoon_users, name='afternoon_users'),
	url(r'^participants/tshirts$', views.tshirts, name='tshirts'),
	url(r'^participants/mailing_list$', views.mailing_list, name='mailing_list'),
	url(r'^participants/checked_in$', views.checked_in, name='checked_in'),
	url(r'^participants/details/(?P<participant_id>[a-z0-9]{16})$', views.participant_details, name='participant_details'),
	url(r'^emails$', views.email_sender, name='email_sender'),
	url(r'^registration$', views.admin_form, name='admin_form'),
	url(r'^query$', views.query_search, name='query_search'),
	url(r'^assistance_form$', views.assistance_form, name='assistance_form'),
	url(r'^assistances$', views.assistance_list, name='assistance_list'),
	url(r'^assistances/pending$', views.pending_assistances, name='pending_assistances'),
	url(r'^assistances/accepted$', views.accepted_assistances, name='accepted_assistances'),
	url(r'^assistances/refused$', views.refused_assistances, name='refused_assistances'),
	url(r'^assistances/served$', views.served_assistances, name='served_assistances'),
	url(r'^assistances/details/(?P<participant_id>[a-z0-9]{16})$', views.assistance_details, name='assistance_details'),
	url(r'^assistances/status/(?P<participant_id>[a-z0-9]{16})$', views.assistance_status, name='assistance_status'),
	
	# REST interfaces
	url(r'^rest/participants/$', views.RESTParticipantList.as_view(), name='rest_participants_list'),
	url(r'^rest/participants/(?P<pk>[a-z0-9]{16})/$', views.RESTParticipantDetails.as_view(), name='rest_participants_details'),
	url(r'^rest/assistances/$', views.RESTAssistanceList.as_view(), name='rest_assistances_list'),
	url(r'^rest/assistances/(?P<pk>[a-z0-9]{16})/$', views.RESTAssistanceDetails.as_view(), name='rest_assistances_details'),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	
	# Access management
	url(r'^accounts/login/$', views.login, name='login'),
	url(r'^accounts/logout/$', views.logout, name='logout'),
)

server/registration_form/registration_form/urls.py
# ----------------------------------------------------------------------- #
# Copyright (C) 2014-2015 Federico "MrModd" Cosentino (http://mrmodd.it/) #
# on behalf of Roma2LUG (http://lug.uniroma2.it/)                         #
# ----------------------------------------------------------------------- #

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'registration_form.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('portal.urls', namespace='portal')),
    url(r'^qr/', include('simple_qrcode.urls', namespace='qrcodes')),
)

server/registration_form/simple_qrcode/urls.py
# ----------------------------------------------------------------------- #
# Copyright (C) 2014-2015 Federico "MrModd" Cosentino (http://mrmodd.it/) #
# on behalf of Roma2LUG (http://lug.uniroma2.it/)                         #
# ----------------------------------------------------------------------- #

from django.conf.urls import patterns, url, include

from simple_qrcode import views

urlpatterns = patterns('',
	
	# Registration form
	url(r'^(?P<qr_id>[a-z0-9]{16})$', views.qrview, name='qrview'),
	url(r'^(?P<qr_id>[a-z0-9]{16})\.svg$', views.qrsvg, name='qrsvg'),
	url(r'^(?P<qr_id>[a-z0-9]{16})\.png$', views.qrpng, name='qrpng'),
)

server/registration_form/portal/models.py
# ----------------------------------------------------------------------- #
# Copyright (C) 2014-2015 Federico "MrModd" Cosentino (http://mrmodd.it/) #
# on behalf of Roma2LUG (http://lug.uniroma2.it/)                         #
# ----------------------------------------------------------------------- #

from django.db import models
from django.conf import settings

# Create your models here.
class Participant(models.Model):
	SIZE_S = 'S'
	SIZE_M = 'M'
	SIZE_L = 'L'
	SIZE_XL = 'XL'
	TSHIRT_SIZE = (
			(SIZE_S, SIZE_S),
			(SIZE_M, SIZE_M),
			(SIZE_L, SIZE_L),
			(SIZE_XL, SIZE_XL),
	)
	
	participant_id = models.CharField(max_length=16, primary_key=True)
	first_name = models.CharField(max_length=128)
	last_name = models.CharField(max_length=128)
	email = models.EmailField(unique=True)
	
	mailing_list = models.BooleanField(default=True)
	tshirt = models.CharField(max_length=2, choices=TSHIRT_SIZE, blank=True, null=True)
	
	participate_morning = models.BooleanField(default=False)
	participate_afternoon = models.BooleanField(default=False)
	
	registration_date = models.DateTimeField(auto_now_add=True)
	check_in = models.DateTimeField(blank=True, null=True)
	
	comments = models.TextField(blank=True)
	
	def __str__(self):
		return str(self.first_name) + ' ' + str(self.last_name)

class Assistance(models.Model):
	PC_DESKTOP = 'dt'
	PC_LAPTOP = 'lt'
	PC_CHROMEBOOK = 'cb'
	PC_TRANSFORMER = 'tf'
	PC_OTHER = 'oo'
	PC_TYPES = (
			(PC_DESKTOP, 'Fisso'),
			(PC_LAPTOP, 'Portatile generico'),
			(PC_CHROMEBOOK, 'Chromebook'),
			(PC_TRANSFORMER, 'Trasformabile (con touchscreen)'),
	)
	
	REFUSED = '0'
	ACCEPTED = '1'
	STATUS = (
			(REFUSED, 'Rifiutata'),
			(ACCEPTED, 'Accettata'),
	)
	participant = models.OneToOneField(Participant, primary_key=True)
	pc_type = models.CharField(max_length=2, choices=PC_TYPES, default=PC_LAPTOP)
	brand = models.CharField(max_length=32)
	model = models.CharField(max_length=32, blank=True, null=True)
	cpu = models.CharField(max_length=32, blank=True, null=True)
	ram = models.CharField(max_length=32, blank=True, null=True)
	
	problem = models.TextField()
	
	preferred_time = models.TimeField(blank=True, null=True)
	acceptance = models.CharField(max_length=1, choices=STATUS, blank=True, null=True)
	accepted_time = models.TimeField(blank=True, null=True)
	estimated_mttr = models.IntegerField(blank=True, null=True)
	
	operator = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
	
	def __str__(self):
		return 'Assistenza per ' + str(self.participant.first_name) + ' ' + str(self.participant.last_name)

class AdminProperty(models.Model):
	key = models.CharField(max_length=32, primary_key=True)
	value = models.CharField(max_length=32)
	
	def __str__(self):
		return '{\'' + str(self.key) + '\': \'' + str(self.value) + '\'}'

server/registration_form/portal/views.py
# ----------------------------------------------------------------------- #
# Copyright (C) 2014-2015 Federico "MrModd" Cosentino (http://mrmodd.it/) #
# on behalf of Roma2LUG (http://lug.uniroma2.it/)                         #
# ----------------------------------------------------------------------- #

# Python basic libraries
import threading
from syslog import syslog as print
from datetime import datetime, date, timedelta

# Django components
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django import forms
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.utils.crypto import get_random_string
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.http import Http404
from django.core import validators
from django.core.exceptions import ObjectDoesNotExist

# Authentication
import django.contrib.auth

# REST
from rest_framework import generics
from rest_framework import permissions

# Email
from django.core.mail import EmailMultiAlternatives, send_mass_mail, send_mail
from email.mime.image import MIMEImage

# QR Code
import qrcode
from qrcode.image.pure import PymagingImage
from io import BytesIO

# Model
from django.db import IntegrityError
from portal.models import Participant, AdminProperty, Assistance
from portal.serializers import ParticipantSerializer, AssistanceSerializer

#####################################################################################################

# Change this if you want to enable/disable emails service
DISABLE_EMAIL = settings.DEBUG
#DISABLE_EMAIL = False

#####################################################################################################

# Support functions and classes

tshirt_date = date(2015, 10, 5) # Consider accepted all reservation < date + 1 day

def generateSerial():
	chars = '0123456789abcdefghijklmnopqrstuvwxyz'
	return get_random_string(16, chars)

def getUniqueParticipantID():
	participant_id = generateSerial()
	while Participant.objects.filter(participant_id=participant_id).exists():
		participant_id = generateSerial()
	return participant_id

def send_registration_email(participant):
	# Generate QRCode
	img = qrcode.make(participant.participant_id, image_factory=PymagingImage)
	img_stream = BytesIO()
	img.save(img_stream, 'PNG')
	
	# Compose email
	subject = 'ID registrazione Linux Day Roma 2015'
	try:
		from_email = settings.EMAIL_CANONICAL_NAME + ' <' + settings.EMAIL_HOST_USER + '>'
	except AttributeError:
		from_email = settings.EMAIL_HOST_USER
	to_email = str(participant) + ' <' + participant.email + '>'
	
	text = 'Caro ' + participant.first_name + ',\n'
	text += 'grazie per esserti iscritto al nostro Linux Day.\n'
	text += 'Ti preghiamo di conservare questa email come promemoria e di mostrarla quando ti verra\' richiesto.\n\n'
	text += 'Linux Day Roma\n'
	text += '24 Ottobre 2015\n'
	text += 'Facolta\' di Ingegneria, Universita\' Tor Vergata\n'
	text += 'Via del Politecnico 1, edificio della Didattica.\n'
	text += 'ID registrazione: ' + str(participant.participant_id) + '\n\n'
	text += 'A presto,\nRoma2LUG e LugRoma3.\n'
	
	html = '<p>Caro ' + participant.first_name + ',<br />\n'
	html += 'grazie per esserti iscritto al nostro Linux Day.<br />\n'
	html += 'Ti preghiamo di conservare questa email come promemoria e di mostrarla quando ti verra\' richiesto.</p>\n'
	html += '<p><a href="http://lug.uniroma2.it/ld15/">Linux Day Roma</a><br />\n'
	html += '24 Ottobre 2015<br />\n'
	html += 'Facolta\' di Ingegneria, Universita\' Tor Vergata<br />\n'
	html += 'Via del Politecnico 1, edificio della Didattica.<br /></p>\n'
	html += '<p>ID registrazione: <b>' + str(participant.participant_id) + '</b><br />\n'
	html += '<img src="cid:qrcode"></p>\n'
	html += '<p>A presto,<br />Roma2LUG e LugRoma3.</p>\n'
	
	# Add content to email
	mail = EmailMultiAlternatives(subject, text, from_email, [to_email,])
	mail.attach_alternative(html, 'text/html')
	image = MIMEImage(img_stream.getvalue(), 'png')
	image.add_header('Content-ID', '<qrcode>') # This is the ID used in tag <img> for HTML part of the email
	mail.attach(image)
	
	mail.send(fail_silently=False)

def send_assistance_email(assistance):
	# Compose email
	subject = 'Linux Day 2015: aggiornamento stato richiesta di assistenza'
	try:
		from_email = settings.EMAIL_CANONICAL_NAME + ' <' + settings.EMAIL_HOST_USER + '>'
	except AttributeError:
		from_email = settings.EMAIL_HOST_USER
	to_email = str(assistance.participant) + ' <' + assistance.participant.email + '>'
	
	status = '--'
	for s in Assistance.STATUS:
		if s[0] == assistance.acceptance:
			status = s[1]
	
	text = 'Caro ' + assistance.participant.first_name + ',\n'
	text += 'ti informiamo che la tua richiesta di assistenza ha cambiato stato ed è stata ' + status + '.\n'
	if assistance.acceptance == Assistance.ACCEPTED:
		text += 'L\'appuntamento è stato fissato per le ' + assistance.accepted_time + '.\n'
		text += 'Ricordati di presentare la tua email di registrazione all\'ingresso e di nuovo al banchetto assistenze.\n\n'
	else:
		text += 'Per avere maggiori informazioni sul perché, contattaci all\'indirizzo roma2lug@gmail.com\n'
		text += 'specificando il tuo ID  di registrazione: ' + assistance.participant.participant_id + '.\n\n'
	text += 'A presto,\nRoma2LUG e LugRoma3.\n'
	
	html = '<p>Caro ' + assistance.participant.first_name + ',<br />\n'
	html += 'ti informiamo che la tua richiesta di assistenza ha cambiato stato ed è stata <b>' + status + '</b>.<br />\n'
	if assistance.acceptance == Assistance.ACCEPTED:
		html += 'L\'appuntamento è stato fissato per le ' + assistance.accepted_time + '.<br />\n'
		html += 'Ricordati di presentare la tua email di registrazione all\'ingresso e di nuovo al banchetto assistenze.</p>\n'
	else:
		html += 'Per avere maggiori informazioni sul perché, contattaci all\'indirizzo roma2lug@gmail.com<br />\n'
		html += 'comunicando il tuo ID di registrazione: <b>' + assistance.participant.participant_id + '</b>.</p>\n'
	html += '<p>A presto,<br />Roma2LUG e LugRoma3.</p>\n'
	
	send_mail(subject, text, from_email, [to_email,], fail_silently=False, html_message=html)

# Send a generic email to participant(s)
def send_email(participants, subject, message):
	try:
		from_email = settings.EMAIL_CANONICAL_NAME + ' <' + settings.EMAIL_HOST_USER + '>'
	except AttributeError:
		from_email = settings.EMAIL_HOST_USER
	
	email_list = []
	for p in participants:
		email = str(p) + ' <' + p.email + '>'
		email_list.append((subject, message, from_email, [email,]))
	email_tuples = tuple(email_list)
	
	send_mass_mail(email_tuples, fail_silently=False)

# Given a search keyword(s) find all possible participants that match
def do_search(query):
	# Check if it is an ID
	if Participant.objects.filter(participant_id=query).exists():
		return Participant.objects.filter(participant_id=query)
	
	# Check if it is an email
	if '@' in query and Participant.objects.filter(email=query).exists():
		return Participant.objects.filter(email=query)
	
	p = []
	# Try the whole query as name
	p.extend(Participant.objects.filter(first_name__icontains=query)) # icontains: contains (substring) case insensitive
	p.extend(Participant.objects.filter(last_name__icontains=query))
	if len(p) > 0:
		return list(set(p)) # Get unique elements
	
	# No results yet: try splitting the query and check for name pieces
	substr = query.split()
	for s in substr:
		p.extend(Participant.objects.filter(first_name__icontains=s)) # icontains: contains (substring) case insensitive
		p.extend(Participant.objects.filter(last_name__icontains=s))
	
	return list(set(p)) # Get unique elements

PARTICIPATIONS = [
	[0, 'Mattina'],
	[1, 'Pomeriggio'],
	[2, 'Mattina e pomeriggio'],
]
TSHIRT = [
	['', 'Nessuna maglietta'],
	[Participant.SIZE_S, Participant.SIZE_S],
	[Participant.SIZE_M, Participant.SIZE_M],
	[Participant.SIZE_L, Participant.SIZE_L],
	[Participant.SIZE_XL, Participant.SIZE_XL],
]

# Registration form fields
class RegistrationForm(forms.Form):
	first_name = forms.CharField(label='Nome*', max_length=128, required=True)
	last_name = forms.CharField(label='Cognome*', max_length=128, required=True)
	email = forms.EmailField(label='Email*', required=True)
	participates = forms.ChoiceField(label='Partecipazione', choices=PARTICIPATIONS, required=False)
	comments = forms.CharField(label='Commenti', max_length=512, widget=forms.Textarea, required=False)
	tshirt = forms.ChoiceField(label='Prenota maglietta', help_text='Prezzo finale inferiore ai 10€. Attenzione, prenotazioni successive alla data '
			+ tshirt_date.strftime("%d/%m/%y") + ' potrebbero non essere garantite.', choices=TSHIRT, initial=False, required=False)
	mailing_list = forms.BooleanField(label='Consenti di ricevere email riguardanti il Linux Day come variazioni sul programma o eventi speciali.', initial=True, required=False)

# Registration form fields for administrators
class AdminRegistrationForm(forms.Form):
	first_name = forms.CharField(label='Nome*', max_length=128, required=True)
	last_name = forms.CharField(label='Cognome*', max_length=128, required=True)
	email = forms.EmailField(label='Email*', required=True)
	mailing_list = forms.BooleanField(label='Consenti di ricevere email riguardanti il Linux Day.', initial=True, required=False)

# Registration form fields for assistance requests
class AssistanceForm(forms.Form):
	email = forms.EmailField(label='Email*', help_text='Deve corrispondere a quella utilizzata in fase di registrazione.', required=True)
	pc_type = forms.ChoiceField(label='Tipo di computer*', choices=Assistance.PC_TYPES)
	brand = forms.CharField(label='Marca*', max_length=32, required=True)
	model = forms.CharField(label='Modello', max_length=32, required=False)
	cpu = forms.CharField(label='Processore', max_length=32, required=False)
	ram = forms.CharField(label='RAM', max_length=32, required=False)

server/registration_form/portal/templates/portal/assistance.html
{% extends 'portal/base_template.html' %}
{% load staticfiles %}
{% load portal_filters %}{# See templatetags/portal_filters.py for filter definition #}

{% block description %}Linux Day{% endblock %}
{% block title %}{{ assistance.participant }}{% endblock %}
{% block content %}

		<div class="row">
			<div class="col-sm-12"><h2>Assistenza per <a href="{% url 'portal:participant_details' participant_id=assistance.participant.participant_id %}">{{ assistance.participant }}</a></h2></div>
		</div>
		
		<div class="row">
			<div class="col-sm-12">
				<table class="table table-striped table-bordered">
					<tbody>
						<tr>
							<th><b>Tipo PC</b>:</th><th>{{ assistance.pc_type|pc_type }}</th>
						</tr>
						<tr>
							<th><b>Marca</b>:</th><th>{{ assistance.brand }}</th>
						</tr>
						<tr>
							<th><b>Modello</b>:</th><th>{{ assistance.model }}</th>
						</tr>
						<tr>
							<th><b>CPU</b>:</th><th>{{ assistance.cpu }}</th>
						</tr>
						<tr>
							<th><b>RAM</b>:</th><th>{{ assistance.ram }}</th>
						</tr>
						<tr>
							<th><b>Problema</b>:</th><th>{{ assistance.problem }}</th>
						</tr>
						<tr>
							<th><b>Preferenza d'orario</b>:</th><th>{{ assistance.preferred_time }}</th>
						</tr>
						<tr>
							<th><b>Stato d'accettazione</b>:</th><th>{{ assistance.acceptance|acceptance_status }} <a href="{% url 'portal:assistance_status' participant_id=assistance.participant.participant_id %}">Cambia stato</a></th>
						</tr>
						{% if assistance.acceptance == assistance.ACCEPTED %}
						<tr>
							<th><b>Orario appuntamento</b>:</th><th>{{ assistance.accepted_time }}</th>
						</tr>
						<tr>
							<th><b>Tempo stimato di intervento</b>:</th><th>{{ assistance.estimated_mttr }} ore</th>
						</tr>
						<tr>
							<th><b>Operatore</b>:</th><th>{% if not assistance.operator %}<a href="{% url 'portal:assistance_details' participant_id=assistance.participant.participant_id %}?get_assistance=true">Prendi assistenza</a>{% else %}{{ assistance.operator }}{% if assistance.operator == user %} <a href="{% url 'portal:assistance_details' participant_id=assistance.participant.participant_id %}?get_assistance=false">Annulla</a>{% endif %}{% endif %}</th>
						</tr>
						{% endif %}
					</tbody>
				</table>
			</div>
		</div>

{% endblock %}

server/registration_form/portal/templates/portal/emails.html
{% extends 'portal/base_template.html' %}
{% load staticfiles %}

{% block description %}Linux Day{% endblock %}
{% block title %}Invio email{% endblock %}
{% block content %}

	{% if confirm_message %}
		<div class="row">
			<div class="col-sm-12"><h2>{{ confirm_message }}</h2></div>
		</div>
        <div class="row">
			<div class="col-sm-12"><h4><a href="{% url 'portal:index' %}">Clicca qui</a> per tornare alla home page.</h4></div>
		</div>
	{% else %}
		<div class="row">
			<div class="col-sm-12"><h2>Invia email</h2></div>
		</div>
		
		<div class="spacer"></div>
		
		<form class="form-horizontal" method="post" action="{% url 'portal:email_sender' %}" onsubmit="return confirm('Sicuro di voler continuare?\nL\'email arriverà a {{ to }}.');">
			{% csrf_token %}
			
			<div class="form-group">
				<label class="control-label col-sm-2 col-lg-2" for="from">Da:</label>
				<div class="col-sm-10 col-lg-10">
					<input class="form-control" id="id_from" name="from" type="text" value="{{ from }}" disabled>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2 col-lg-2" for="to">A:</label>
				<div class="col-sm-10 col-lg-10">
					<input class="form-control" id="id_to" name="to" type="text" value="{{ to }}" disabled>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2 col-lg-2" for="subject">Oggetto:</label>
				<div class="col-sm-10 col-lg-10">
					<input class="form-control" id="id_subject" name="subject" type="text" maxlength="128" required>
				</div>
			</div>
			<div class="form-group">
				<label class="control-label col-sm-2 col-lg-2" for="message">Messaggio:</label>
				<div class="col-sm-10 col-lg-10">
					<textarea class="form-control" id="id_message" name="message" cols="40" rows="10" maxlength="1024" required></textarea>
				</div>
			</div>
			
			<div class="row">
				<div class="col-sm-10 col-sm-offset-2">
					<button type="submit" class="btn btn-primary btn-block">Invia</button>
				</div>
			</div>
			
			<input type="hidden" id="id_participant_id" name="participant_id" value="{{ participant_id }}" />
		</form>
	{% endif %}
		
{% endblock %}

server/registration_form/portal/templates/portal/index.html
{% extends 'portal/base_template.html' %}
{% load staticfiles %}
{% load bootstrap %}

{% block description %}Linux Day{% endblock %}
{% block title %}Pagina di registrazione{% endblock %}
{% block content %}

{% if user.is_authenticated %}
		{% if public_form_disabled %}
		<div class="row">
			<div class="col-sm-12 col-lg-12">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Chiudi"><span aria-hidden="true">&times;</span></button>
					<b>Attenzione</b>: il modulo di registrazione non &egrave; attivo! <a href="{% url 'portal:index' %}?disable_form=false">Abilita ora.</a>
				</div>
			</div>
		</div>
		{% endif %}
		{% if assistances_disabled %}
		<div class="row">
			<div class="col-sm-12 col-lg-12">
				<div class="alert alert-danger alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Chiudi"><span aria-hidden="true">&times;</span></button>
					<b>Attenzione</b>: il modulo di prenotazione per le assistenze non &egrave; attivo! <a href="{% url 'portal:index' %}?disable_assistances=false">Abilita ora.</a>
				</div>
			</div>
		</div>
		{% endif %}
		
		<div class="row">
			<div class="col-sm-12"><h2>Pagina riassuntiva</h2></div>
		</div>
		
		<div class="row">
			<div class="col-sm-12">
				<table class="table table-striped table-bordered">
					<tbody>
						<tr>
							<th><b>Utenti registrati</b>:</th><th><a href="{% url 'portal:participants' %}">{{ registered_users }}</a></th>
						</tr>
						<tr>
							<th><b>Partecipanti la mattina</b>:</th><th><a href="{% url 'portal:morning_users' %}">{{ morning_users }}</a></th>
						</tr>
						<tr>
							<th><b>Partecipanti il pomeriggio</b>:</th><th><a href="{% url 'portal:afternoon_users' %}">{{ afternoon_users }}</a></th>
						</tr>
						<tr>
							<th><b>Magliette</b>:</th><th><a href="{% url 'portal:tshirts' %}">{{ tshirts }}</a></th>
						</tr>
						<tr>
							<th><b>Utenti abilitati a ricevere email</b>:</th><th><a href="{% url 'portal:mailing_list' %}">{{ mailable_users }}</a></th>
						</tr>
						<tr>
							<th><b>Presenze</b>:</th><th><a href="{% url 'portal:checked_in' %}">{{ seen_users }}</a></th>
						</tr>
						<tr>
							<th><b>Assistenze pendenti</b>:</th><th><a href="{% url 'portal:pending_assistances' %}">{{ pending_assistances }}</a></th>
						</tr>
						<tr>
							<th><b>Assistenze accettate</b>:</th><th><a href="{% url 'portal:accepted_assistances' %}">{{ accepted_assistances }}</a></th>
						</tr>
						<tr>
							<th><b>Assistenze rifiutate</b>:</th><th><a href="{% url 'portal:refused_assistances' %}">{{ refused_assistances }}</a></th>
						</tr>
						<tr>
							<th><b>Assistenze servite</b>:</th><th><a href="{% url 'portal:served_assistances' %}">{{ served_assistances }}</a></th>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
{% else %}
		<div class="row">
			<div class="col-sm-12"><h2>24 Ottobre, Facolt&agrave; di Ingegneria<br />Universit&agrave; di Roma Tor Vergata</h2></div>
		</div>
		
		<div class="spacer"></div>
	{% if public_form_disabled %}
		<div class="row">
			<div class="col-sm-12"><h3>Il modulo di registrazione non &egrave; attualmente attivo.</h3></div>
		</div>
	{% else %}
		<form class="form-horizontal" method="post" action="{% url 'portal:index' %}">
			<legend>Modulo di registrazione. Informaci della tua presenza!</legend>
			{% csrf_token %}
			
			{% if errors %}
			<div class="col-sm-10 col-lg-10 col-sm-offset-2">
				<div class="alert alert-warning alert-dismissible" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Chiudi"><span aria-hidden="true">&times;</span></button>
					<strong>Attenzione</strong>: l'email usata sembra essere gi&agrave; presente nel nostro sistema.
					Se ritieni che si sia verificato un errore contattaci all'indirizzo <a href="mailto:roma2lug@gmail.com">roma2lug@gmail.com</a>.
					Altrimenti <a href={% url 'portal:index' %}>torna indietro</a> e riprova con un altro indirizzo.
				</div>
			</div>
			{% endif %}
			
			{{ form|bootstrap_horizontal }}
			<div class="row">
				<div class="col-sm-10 col-sm-offset-2">
					<button type="submit" class="btn btn-primary btn-block">Registra</button>
				</div>
			</div>
		</form>
		{% if not assistances_disabled %}
		<legend style="padding-top: 20px;"></legend>
		<div class="row">
			<div class="col-sm-10 col-lg-10 col-sm-offset-2 comment">
				Vuoi ricevere assistenza durante il Linux Day? Registrati e poi compila il nostro modulo a <a href="{% url 'portal:assistance_form' %}">questo indirizzo</a>.
			</div>
		</div>
		{% endif %}
	{% endif %}
{% endif %}
		
{% endblock %}